#ifndef DEF_CONSTANTES
#define DEF_CONSTANTES

#define WIDTH_WINDOW 960
#define HEIGHT_WINDOW 960

#define TEX_REIMU_FRONT 0
#define TEX_REIMU_BACK 1
#define TEX_REIMU_LEFT 2
#define TEX_REIMU_RIGHT 3
#define TEX_MUR 4
#define TEX_CAISSE 5
#define TEX_CAISSE_OK 6
#define TEX_INTERRUPTEUR 7
#define TEX_BACKGROUND 8

#define DOWN 0
#define UP 1
#define LEFT 2
#define RIGHT 3

#define NOMBRE_CASES_AXE_VERTICAL 12
#define NOMBRE_CASES_AXE_HORIZONTAL 12

#define NOMBRE_NIVEAUX 4

#endif // DEF_CONSTANTES
